name: ğŸ§  LeetCode Sync

on:
  schedule:
    - cron: '0 2 * * *' # æ¯æ—¥ 10:00 (å°ç£æ™‚é–“)
  workflow_dispatch:

jobs:
  leetcode-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Sync LeetCode Submissions
        uses: shihanng/leetcode-export@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          session: ${{ secrets.LEETCODE_SESSION }}
          csrftoken: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          language: python3